package com.example.codecrafthub;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Service layer responsible for course operations and JSON file storage.
 *
 * This class stores all courses in a file named courses.json.
 */
@Service
@RequiredArgsConstructor
public class CourseService {

    /**
     * Jackson object used to read and write JSON.
     *
     * Spring Boot automatically configures this ObjectMapper with support
     * for Java time classes such as LocalDate and Instant.
     */
    private final ObjectMapper objectMapper;

    /**
     * The JSON file used as the application's data store.
     */
    private final Path dataFile = Path.of("courses.json");

    /**
     * An in-memory list containing the courses currently loaded from disk.
     */
    private List<Course> courses = new ArrayList<>();

    /**
     * Creates courses.json when the application starts if it does not exist.
     */
    @PostConstruct
    public synchronized void initialize() {
        try {
            if (Files.notExists(dataFile)) {
                courses = new ArrayList<>();
                writeCoursesToFile();
                return;
            }

            String json = Files.readString(dataFile);

            if (json == null || json.isBlank()) {
                courses = new ArrayList<>();
                writeCoursesToFile();
                return;
            }

            courses = objectMapper.readValue(
                    json,
                    new TypeReference<List<Course>>() {
                    }
            );

            if (courses == null) {
                courses = new ArrayList<>();
            }

        } catch (IOException exception) {
            throw new CourseFileException(
                    "Unable to read courses.json during application startup",
                    exception
            );
        }
    }

    /**
     * Returns all courses.
     */
    public synchronized List<Course> getAllCourses() {
        // Return a copy so callers cannot directly modify the internal list.
        return new ArrayList<>(courses);
    }

    /**
     * Finds one course by ID.
     */
    public synchronized Course getCourseById(Long id) {
        return courses.stream()
                .filter(course -> course.getId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CourseNotFoundException(id));
    }

    /**
     * Adds a new course.
     *
     * The ID and creation timestamp are generated by the server.
     */
    public synchronized Course createCourse(Course incomingCourse) {
        validateCourse(incomingCourse);

        Course newCourse = Course.builder()
                .id(getNextId())
                .name(incomingCourse.getName().trim())
                .description(incomingCourse.getDescription().trim())
                .targetDate(incomingCourse.getTargetDate())
                .status(incomingCourse.getStatus())
                .createdAt(Instant.now())
                .build();

        courses.add(newCourse);
        writeCoursesToFile();

        return newCourse;
    }

    /**
     * Updates an existing course.
     *
     * The original ID and created_at value are preserved.
     */
    public synchronized Course updateCourse(Long id, Course incomingCourse) {
        validateCourse(incomingCourse);

        Course existingCourse = getCourseById(id);

        existingCourse.setName(incomingCourse.getName().trim());
        existingCourse.setDescription(incomingCourse.getDescription().trim());
        existingCourse.setTargetDate(incomingCourse.getTargetDate());
        existingCourse.setStatus(incomingCourse.getStatus());

        writeCoursesToFile();

        return existingCourse;
    }

    /**
     * Deletes a course by ID.
     */
    public synchronized void deleteCourse(Long id) {
        Course course = getCourseById(id);

        courses.remove(course);
        writeCoursesToFile();
    }

    /**
     * Generates the next course ID.
     *
     * IDs begin at 1. Deleted IDs are not reused.
     */
    private Long getNextId() {
        return courses.stream()
                .map(Course::getId)
                .filter(id -> id != null)
                .max(Comparator.naturalOrder())
                .orElse(0L) + 1;
    }

    /**
     * Validates fields required by both POST and PUT requests.
     */
    private void validateCourse(Course course) {
        if (course == null) {
            throw new InvalidCourseException("Request body is required");
        }

        if (course.getName() == null || course.getName().isBlank()) {
            throw new InvalidCourseException("The name field is required");
        }

        if (course.getDescription() == null
                || course.getDescription().isBlank()) {
            throw new InvalidCourseException(
                    "The description field is required"
            );
        }

        if (course.getTargetDate() == null) {
            throw new InvalidCourseException(
                    "The target_date field is required"
            );
        }

        if (course.getStatus() == null) {
            throw new InvalidCourseException("The status field is required");
        }
    }

    /**
     * Writes the current in-memory courses to courses.json.
     *
     * A temporary file is used first. It is then moved over the original file.
     * This reduces the risk of leaving a partially written JSON file.
     */
    private void writeCoursesToFile() {
        Path temporaryFile = Path.of("courses.json.tmp");

        try {
            String json = objectMapper
                    .writerWithDefaultPrettyPrinter()
                    .writeValueAsString(courses);

            Files.writeString(temporaryFile, json);

            try {
                Files.move(
                        temporaryFile,
                        dataFile,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE
                );
            } catch (java.nio.file.AtomicMoveNotSupportedException exception) {
                // Some operating systems do not support atomic moves.
                // A normal replacement still safely updates the file.
                Files.move(
                        temporaryFile,
                        dataFile,
                        StandardCopyOption.REPLACE_EXISTING
                );
            }

        } catch (IOException exception) {
            throw new CourseFileException(
                    "Unable to write courses.json",
                    exception
            );
        }
    }

    /**
     * Flushes all current changes before Spring shuts down.
     *
     * Every create, update, and delete already writes immediately. This
     * additional flush ensures the current state is persisted during shutdown.
     */
    @PreDestroy
    public synchronized void flushBeforeShutdown() {
        writeCoursesToFile();
    }

    /**
     * Thrown when a requested course does not exist.
     */
    public static class CourseNotFoundException extends RuntimeException {

        public CourseNotFoundException(Long id) {
            super("Course with ID " + id + " was not found");
        }
    }

    /**
     * Thrown when a request is missing required fields.
     */
    public static class InvalidCourseException extends RuntimeException {

        public InvalidCourseException(String message) {
            super(message);
        }
    }

    /**
     * Thrown when courses.json cannot be read or written.
     */
    public static class CourseFileException extends RuntimeException {

        public CourseFileException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
