package com.codecrafthub;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Represents a course in CodeCraftHub.
 *
 * The Java field names use camelCase, while Jackson annotations map them
 * to the snake_case names required by the JSON API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    /**
     * The course ID is generated by the server.
     */
    @JsonProperty("id")
    private Long id;

    /**
     * Course name.
     */
    @JsonProperty("name")
    private String name;

    /**
     * Course description.
     */
    @JsonProperty("description")
    private String description;

    /**
     * Target completion date.
     *
     * JSON format:
     * "2026-12-31"
     */
    @JsonProperty("target_date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate targetDate;

    /**
     * Current course status.
     */
    @JsonProperty("status")
    private CourseStatus status;

    /**
     * Automatically generated creation timestamp.
     *
     * Example:
     * "2026-09-25T12:30:00Z"
     */
    @JsonProperty("created_at")
    private Instant createdAt;

    /**
     * The only allowed course status values.
     *
     * @JsonValue controls how the enum is written to JSON.
     * @JsonCreator controls how incoming JSON is converted to the enum.
     */
    public enum CourseStatus {

        NOT_STARTED("Not Started"),
        IN_PROGRESS("In Progress"),
        COMPLETED("Completed");

        private final String displayValue;

        CourseStatus(String displayValue) {
            this.displayValue = displayValue;
        }

        /**
         * Writes the exact required text into JSON responses.
         */
        @JsonValue
        public String getDisplayValue() {
            return displayValue;
        }

        /**
         * Reads and validates the exact status text from JSON requests.
         */
        @JsonCreator
        public static CourseStatus fromValue(String value) {
            for (CourseStatus status : CourseStatus.values()) {
                if (status.displayValue.equals(value)) {
                    return status;
                }
            }

            throw new IllegalArgumentException(
                    "Status must be exactly one of: " +
                    "\"Not Started\", \"In Progress\", or \"Completed\""
            );
        }
    }
}
